name: Deploy Static Pages

on:
  push:
    branches:
      - main  
      - mvp2.1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Copy Exported Pages
      run: |
        mkdir public
        cp -r dashboard/exported_pages/* public/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public