name: Deploy Static Pages
run-name: Deploy Static Pages on Update

on:
  push:
    branches:
      - main
      - mvp2.1

jobs:
  prepare-pages:
    name: Prepare Static Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install dependencies using Requirements.txt
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Generate HTML Pages
        run: |
          python dashboard/utils/export_html.py

      - name: Upload Static Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dashboard/exported_pages"

  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: prepare-pages
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2