name: Fetch Airtable Table and Convert to CSV

# Trigger the workflow manually and accept inputs
on:
  workflow_dispatch:
    inputs:
      airtable_base_id:
        description: 'The ID of the Airtable base'
        required: true
        type: string
      table_name:
        description: 'The name of the table to fetch'
        required: true
        type: string
      output_file:
        description: 'The name of the output CSV file (optional)'
        required: false
        type: string

jobs:
  fetch_table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you prefer

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_airtable.py
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python scripts/fetch_airtable.py \
            --base_id "${{ github.event.inputs.airtable_base_id }}" \
            --table_name "${{ github.event.inputs.table_name }}" \
            --output "${{ github.event.inputs.output_file }}"

      - name: Upload Fetched CSV as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: airtable-data-${{ github.event.inputs.table_name }}
          path: ${{ github.event.inputs.output_file || github.event.inputs.table_name + '.csv' }}
