name: Fetch Airtable Tables and Convert to CSVs

# Trigger the workflow on push to the specific file or manually
on:
  push:
    paths:
      - 'data/airtable_api_identifiers.csv'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  fetch_table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you prefer

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      - name: Run fetch_airtables.py
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python scripts/fetch_airtables.py $AIRTABLE_API_KEY

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "*** Update Airtable CSVs" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}  # This refers to the current branch
          title: "Update CSV files from Airtable"
          body: "This PR updates the CSV files based on the latest data from Airtable."
          base: create-CSVs  # Adjust this to your desired base branch
