name: Fetch Airtable Table and Convert to CSV

# Trigger the workflow manually and accept inputs
on:
  workflow_dispatch:
    # inputs:
    #   airtable_base_id:
    #     description: 'The ID of the Airtable base'
    #     required: true
    #     type: string
    #   airtable_table_id:
    #     description: 'The ID of the Airtable table'
    #     required: true
    #     type: string

jobs:
  fetch_table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you prefer

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      - name: Run fetch_airtable.py
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          python scripts/fetch_airtable.py $AIRTABLE_API_KEY
          
      - name: Push New CSV to branch
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Action (Adding file to Python)'
          git config --global user.email 'aliisona@users.noreply.github.com'
          git commit -am "Adding CSV files"
          git push  

