name: Fetch Airtable Tables and Convert to CSVs

# Trigger the workflow on push to the specific file
on:
  push:
    paths:
      - 'data/airtable_api_identifiers.csv'
  workflow_dispatch:

jobs:
  fetch_table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you prefer

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyairtable

      - name: Run fetch_airtables.py
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python scripts/fetch_airtables.py $AIRTABLE_API_KEY

      - name: Create a new branch
        run: |
          git checkout -b update-airtable-csv-${{ github.run_id }}

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action (Adding file to Python)'
          git config --global user.email 'aliisona@users.noreply.github.com'
          git add *
          git commit -am "Update CSV files from Airtable"

      - name: Check for file existence
        run: ls -R data
      
      - name: Check git status
        run: git status
      
      - name: Show last commit
        run: git show --name-status

      - name: Push changes to the new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --set-upstream origin update-airtable-csv-${{ github.run_id }}

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-airtable-csv-${{ github.run_id }}
          title: "Update CSV files from Airtable"
          body: "This PR updates the CSV files based on the latest data from Airtable."
          base: create-CSVs
