name: Get stats

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * *'

jobs:
  publications:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout persist credentials
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Install dependencies
        run: |
          pip install pyairtable

      - name: Update Repositories AirTable table
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

        run: |
          python scripts/collect_github_repository_stats.py $GITHUB_API_TOKEN $AIRTABLE_API_KEY

      - name: Update Publications AirTable table
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

        run: |
          python scripts/google_scholar_citations.py $AIRTABLE_API_KEY


