name: Models scan

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * *'

jobs:
  scan-ersilia-model-hub:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout persist credentials
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Install dependencies
        run: |
          pip install pyairtable

      - name: List EOS repositories
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh search repos eos --owner=ersilia-os --visibility=public --json name -L 1000 --match name > ersilia_model_repos.json
          python -c "import json; f = open('ersilia_model_repos.json', 'r'); data = json.load(f); f.close(); model_ids = [d['name'] for d in data if d['name'].startswith('eos') and len(d['name']) == 7]; f = open('ersilia_model_repos.txt', 'w'); f.write('\n'.join(model_ids)); f.close()"
          
      - name: Find which repositories do not exist in AirTable and viceversa
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python scripts/scan_model_repositories_in_airtable.py ersilia_model_repos.txt $AIRTABLE_API_KEY nonregistered_model_repos.txt nonexistent_model_registries.txt

      - name: Read non-registered model repositories and create an issue for each of them
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_OWNER="ersilia-os"
          REPO_NAME="ersilia"

      - name: Read Model IDs and Create Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_OWNER="ersilia-os"
          REPO_NAME="ersilia"

          while IFS= read -r MODEL_ID; do
            ISSUE_TITLE="🚨 Model $MODEL_ID repository not registered in AirTable 🚨"

            ISSUE_BODY=$'Hi! 👋\n\nThe model [$MODEL_ID](https://github.com/ersilia-os/$MODEL_ID) has an associated repository in the [ersilia-os](https://github.com/ersilia-os) organization profile, but there is **no registered record in the AirTable base.**\n\nPlease consider removing this repository from ersilia-os since it is anyway not accessible from the Ersilia CLI if no AirTable record is available.\n\nThank you! 🙏'
            
            # Check if issue already exists
            if gh issue list --repo $REPO_OWNER/$REPO_NAME --search "$ISSUE_TITLE in:title" | grep -q "$ISSUE_TITLE"; then
              echo "Issue already exists for $MODEL_ID"
            else
              # Create new issue
              gh issue create --title "$ISSUE_TITLE" \
                              --body "$ISSUE_BODY" \
                              --label "bug" \
                              --repo $REPO_OWNER/$REPO_NAME
            fi
          done < nonregistered_model_repos.txt
          
