name: Models scan

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * *'

jobs:
  scan-ersilia-model-hub:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout persist credentials
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: List EOS repositories
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh search repos eos --owner=ersilia-os --visibility=public --json name -L 1000 --match name > ersilia_model_repos.json
          python -c "import json; f = open('ersilia_models.json', 'r'); data = json.load(f); f.close(); model_ids = [d['name'] for d in data]; print(model_ids)"
